CREATE TABLE tickets(
    id                          uuid PRIMARY KEY,
    status_id                   int not null,
    status_timestamp            timestamptz not null,
    flight_id                   uuid not null,
    user_id                     uuid not null,
    passenger_id                uuid not null,
    class_seats_id              uuid not null,
    seat_id                     uuid,
    count_additional_baggage    int not null,
    price                       int not null,
    paid_with_bonuses           int not null,
    accrued_bonuses             int not null,
    FOREIGN KEY (status_id) REFERENCES statuses (id) ON DELETE CASCADE,
    FOREIGN KEY (flight_id) REFERENCES flights (id) ON DELETE CASCADE,
    FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE,
    FOREIGN KEY (passenger_id) REFERENCES passengers (id) ON DELETE CASCADE,
    FOREIGN KEY (class_seats_id) REFERENCES classes_seats (id) ON DELETE CASCADE,
    FOREIGN KEY (seat_id) REFERENCES seats (id) ON DELETE CASCADE
    );