// Code generated by MockGen. DO NOT EDIT.
// Source: homework/internal/service/flights (interfaces: FlightsService)

// Package mock_flights is a generated GoMock package.
package mock_flights

import (
	context "context"
	flights "homework/internal/domain/flights"
	specs "homework/specs"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	uuid "github.com/google/uuid"
)

// MockFlightsService is a mock of FlightsService interface.
type MockFlightsService struct {
	ctrl     *gomock.Controller
	recorder *MockFlightsServiceMockRecorder
}

// MockFlightsServiceMockRecorder is the mock recorder for MockFlightsService.
type MockFlightsServiceMockRecorder struct {
	mock *MockFlightsService
}

// NewMockFlightsService creates a new mock instance.
func NewMockFlightsService(ctrl *gomock.Controller) *MockFlightsService {
	mock := &MockFlightsService{ctrl: ctrl}
	mock.recorder = &MockFlightsServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockFlightsService) EXPECT() *MockFlightsServiceMockRecorder {
	return m.recorder
}

// GetFlightById mocks base method.
func (m *MockFlightsService) GetFlightById(arg0 context.Context, arg1 uuid.UUID) (*flights.Flight, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetFlightById", arg0, arg1)
	ret0, _ := ret[0].(*flights.Flight)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetFlightById indicates an expected call of GetFlightById.
func (mr *MockFlightsServiceMockRecorder) GetFlightById(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetFlightById", reflect.TypeOf((*MockFlightsService)(nil).GetFlightById), arg0, arg1)
}

// GetFlights mocks base method.
func (m *MockFlightsService) GetFlights(arg0 context.Context, arg1 specs.GetFlightsParams) ([]flights.Flight, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetFlights", arg0, arg1)
	ret0, _ := ret[0].([]flights.Flight)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetFlights indicates an expected call of GetFlights.
func (mr *MockFlightsServiceMockRecorder) GetFlights(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetFlights", reflect.TypeOf((*MockFlightsService)(nil).GetFlights), arg0, arg1)
}
